version: '3.7'

networks:
  byfn:

services:
  ca.trancondsfsdfsdfghau.example.com:
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-trancondsfsdfsdfghau
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.trancondsfsdfsdfghau.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.trancondsfsdfsdfghau.example.com-key.pem
    ports:
      - "11489:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/trancondsfsdfsdfghau:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.trancondsfsdfsdfghau.example.com
    networks:
      - byfn